logging:
  level:
    ROOT: INFO
    com.albedo.java: ${logback.loglevel}
server:
  port: 8031
  servlet:
    session:
      timeout: 30m

spring:
  redis:
    host: albedo-redis
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/albedo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true





# ===================================================================
# Albedo specific properties
# ===================================================================

application:
  developMode: true
  security:
    authentication:
      jwt:
        # 必须使用最少88位的Base64对该令牌进行编码
        base64-secret: bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
        # Token is valid 24 hours
        token-validity-in-seconds: 300
        token-validity-in-seconds-for-remember-me: 2592000
